- name: Remove nodejs if it's installed
  apt:
    name: nodejs
    state: absent

- name: Add nodesource official GPG key
  apt_key:
    data: "{{ lookup('file', 'nodesource.asc') }}"
    state: present

- name: Run the script to add node to apt repo
  script: files/setup_{{ node_version }}.x

- name: Install nodejs
  apt:
    name: nodejs
    state: present
